source 'https://rubygems.org'
ruby '2.3.4'

gem 'devise'
gem 'figaro'
gem 'jbuilder', '~> 2.0'
gem 'pg'
gem 'puma'
gem 'rails', '5.1.3'
gem 'redis'
gem 'geocoder'
gem 'faker'
gem 'callr'

gem 'autoprefixer-rails'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'jquery-rails'
gem 'sass-rails'
gem 'simple_form'
gem 'uglifier'
gem 'coffee-rails'
gem 'gmaps4rails'
gem 'rails-assets-underscore', source: 'https://rails-assets.org'
gem 'rails-assets-flatpickr', source: 'https://rails-assets.org'
gem 'ladda-bootstrap-rails', :git => 'https://github.com/vendji/ladda-bootstrap-rails.git'
gem 'izimodal'

group :development, :test do
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
